import "./globals.css";
import Page from "./page";
import "./fonts.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className=" w-full">
          <Page />
        </div>
      </body>
    </html>
  );
}
